import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `npm run test:coverage` — gitignored, but ESLint's flat
    // config doesn't read .gitignore on its own.
    "coverage/**",
    // Same story: the cache-round-trip suite's own build output
    // (scripts/run-cache-e2e-server.mjs), plus its Playwright report.
    ".next-cache-e2e/**",
    "playwright-report-cache/**",
  ]),
]);

export default eslintConfig;
