'use client'

import { useEffect, useRef, useState } from 'react'
import { createPortal } from 'react-dom'
import { loadGoogleMaps, MAPS_API_KEY, MAPS_MAP_ID, mapsAuthFailed, onMapsAuthFailure } from '@/lib/loadGoogleMaps'
import { destinationQuery, directionsUrl, type LatLng } from '@/lib/googleMapsLinks'
import { haversineMiles } from '@/lib/geo'
import { community } from '@/community.config'
import type { DirectoryResource } from '@/types'
import { glyphElementFor, glyphTextFor } from '@/lib/categoryIcons'
import { PinIcon } from '@/components/icons'

/** One plottable place on the map. */
export type MapPoint = {
  id: string
  lat: number
  lng: number
  name: string
  address?: string
  phone?: string
  /** Emoji/glyph shown inside the pin (e.g. a category icon). */
  glyph?: string
  /** An uploaded picture shown inside the pin instead of `glyph` — see
   *  CategoryConfig.iconImageUrl. */
  glyphSrc?: string
  /** Pin background color (hex). */
  color: string
  /** Subtitle shown in the info window (e.g. the category label). */
  categoryLabel?: string
  /** Category id used to deep-link into the directory. Absent for hospitals. */
  filterId?: string
  /** The underlying listing, when this point has one (absent for hospitals) —
   *  carried through so a marker tap can show full details without a second
   *  lookup. See MapPlaceDetail. */
  raw?: DirectoryResource
  /** On the visitor's personal "Pinned" shortlist (see lib/pinned.ts) — draws
   *  a small badge on the marker so a pinned place still stands out once the
   *  map is showing dozens of same-category pins. */
  pinned?: boolean
}

const HOSPITALS_FILTER_ID = '__hospitals__'
// How long the selection-reframe logic waits for a real 'idle' event before
// giving up and proceeding anyway — see onIdleOrTimeout's own comment.
const IDLE_FALLBACK_MS = 1500

type Props = {
  points: MapPoint[]
  /** The visitor's live or set location. Rendered as a pulsing blue dot. */
  userLocation?: LatLng | null
  /** Origin for a pin's "Directions ↗" link. Prefers a human-readable label
   *  (typed address, or a listing's name) over raw coordinates — which
   *  Maps otherwise renders as an anonymous "Dropped pin" — so this is
   *  usually text even though `userLocation` above is always coords. Falls
   *  back to `userLocation` itself when the caller has nothing better (e.g.
   *  the admin's category preview, or live GPS mid-tracking). */
  directionsOrigin?: string | LatLng | null
  /** When true the map pans to keep the user centered as their position updates.
   *  When false the marker moves silently without interrupting browsing. */
  follow?: boolean
  /** Called when the user manually taps "Re-center" so the parent can flip
   *  follow back on. */
  onResumeFollow?: () => void
  /** Called the moment the user manually drags the map — the parent flips
   *  `follow` off so their live position stops yanking the view back while
   *  they're trying to look around, same as Google Maps' own blue-dot
   *  behavior (it only resumes centering once they tap the re-center pill). */
  onManualDrag?: () => void
  /** Fallback center when there are no points to fit (e.g. Center City Philly). */
  fallbackCenter?: { lat: number; lng: number }
  /** Called when the user taps "View listing" in an info window. */
  onViewListing?: (categoryId: string, listingId: string) => void
  /** When provided, tapping a marker calls this instead of opening the small
   *  Google info-window bubble — the mobile map uses it to bring up the
   *  bottom sheet's place detail instead, Google-Maps-app-style. Desktop
   *  leaves this unset and keeps the info-window behavior. */
  onSelectPoint?: (point: MapPoint) => void
  /** Called instead of onSelectPoint when the tapped marker is already the
   *  selected one — lets a second tap on the same pin deselect it, same as
   *  tapping "Back to list" or swiping left on its card. */
  onDeselectPoint?: () => void
  /** Tapping empty map (not a marker) — mobile uses this to drop the bottom
   *  sheet back to peek height AND clear any selected place, same as tapping
   *  the pin again would; the pin stops reading as selected too. */
  onBackgroundClick?: () => void
  /** A long-press (touch) or right-click (desktop) on empty map — both fire
   *  as the same 'contextmenu' event, which is the standard way to offer
   *  "drop a pin here" without hijacking the plain single-tap/click that
   *  onBackgroundClick already owns. */
  onMapLongPress?: (coords: LatLng) => void
  /** A press-and-hold (touch) or mouse-hold on an existing marker — distinct
   *  from onMapLongPress, which only fires on empty map. Detected by hand
   *  (pointerdown + a timer) rather than reused from Maps' own 'contextmenu'
   *  synthesis: that event is generated by the Maps SDK for the map's own
   *  container, not per-marker, so there's no existing per-pin long-press
   *  signal to hook into. Suppresses the marker's own subsequent 'gmp-click'
   *  so a long-press doesn't also open/close the place's detail card. */
  onLongPressPoint?: (point: MapPoint) => void
  /** True while a search query or filter chip is narrowing `points` — overrides
   *  the "don't reframe if a user location is set" rule below, so searching
   *  actually takes you to the result(s), same as the Google Maps app. */
  searchActive?: boolean
  /** id of the place currently shown in the mobile sheet, if any — that
   *  marker gets drawn larger so it's clear which listing the sheet is
   *  showing (see the selection-highlight effect below). */
  selectedId?: string
  /** Bumped by the parent only when the current `selectedId` change should
   *  reframe the map (fit user location + the selected pin in view) — a
   *  listing picked from the bottom sheet/sidebar list bumps it, a pin
   *  tapped directly on the map does not, so tapping a pin just highlights
   *  it without moving the camera the visitor already positioned themselves.
   *  Compared against the previously-consumed value, not just truthiness, so
   *  a legitimate reframe request isn't dropped when it happens to repeat
   *  the same number. */
  frameToken?: number
  /** Current px height of the mobile nearby sheet covering the bottom of the
   *  map, if any — a newly-selected pin centers within the remaining visible
   *  strip above it instead of the whole container's center (which the sheet
   *  would otherwise mostly hide it behind). 0 on desktop (no sheet). */
  obscuredBottomPx?: number
  /** Current px height of the floating search bar + category filter chips
   *  covering the top of the map on mobile, if any — narrows the same
   *  "visible strip" a selected pin centers within, since that overlay hides
   *  the top of the map just as surely as the sheet hides the bottom. 0 on
   *  desktop (no floating overlay). */
  obscuredTopPx?: number
  /** Admin-configured cap (site_settings.map_zoom_radius_miles) on how far
   *  a point can be from the visitor (or the community center, if no
   *  location is set) and still count toward the automatic "fit everything"
   *  framing below. Without this, a single far-off listing — e.g. a
   *  delivery-only address miles outside town — could force the whole map
   *  to zoom out to fit it the moment its category was selected. Null/unset
   *  means no cap (every point counts), the original behavior. Outlier
   *  points are still plotted as markers either way (see the loop above,
   *  which is unaffected by this) — they're just excluded from what the
   *  initial view has to include. */
  zoomRadiusMiles?: number | null
}

const DEFAULT_CENTER = community.mapCenter

// Narrows `points` to the ones the automatic "fit everything" framing should
// actually include — see Props.zoomRadiusMiles. `radiusMiles == null` means
// no cap (every point counts), which keeps this a no-op wherever the admin
// hasn't configured one.
/**
 * The identity of a set of points for FRAMING purposes: which places are on
 * the map, regardless of how they look or what order they arrive in.
 *
 * The marker-rebuild effect below runs on every new `points` array and ends by
 * reframing the camera. That conflates two different reasons the array can
 * change. "A different set of places is shown" (a filter, a search) should
 * reframe. "The same places, drawn differently" should not — and pinning is
 * exactly that: allPoints stamps `pinned` on every point and lists pinnedIds
 * in its deps, so toggling one pin rebuilds the whole array.
 *
 * The result was that press-and-holding a marker to pin it zoomed the map out
 * to the whole community. Only visible with no location set, because the
 * reframe is skipped outright when there is one — so the bug hid from anyone
 * who had entered an address.
 *
 * Sorted, because order carries no framing meaning: the same places in a
 * different sequence produce the same bounds, and re-fitting for a reorder is
 * the same unwanted camera move.
 */
export function framingKey(points: Array<{ id: string }>): string {
  return points
    .map((p) => p.id)
    .sort()
    .join('|')
}

export function pointsWithinZoomRadius(points: LatLng[], anchor: LatLng, radiusMiles: number | null | undefined): LatLng[] {
  if (radiusMiles == null) return points
  return points.filter((p) => haversineMiles(anchor, p) <= radiusMiles)
}

// Builds the info-window content as a real DOM node so we can attach event
// listeners (e.g. "View listing") without putting callbacks on window.
function buildInfoContent(
  p: MapPoint,
  onViewListing?: (categoryId: string, listingId: string) => void,
  origin?: string | LatLng | null,
): HTMLElement {
  const s = (el: HTMLElement, css: string) => { el.style.cssText = css; return el }
  const div = (css = '') => s(document.createElement('div'), css)
  const a = (href: string, text: string, css = '') => {
    const el = s(document.createElement('a'), css) as HTMLAnchorElement
    el.href = href; el.textContent = text
    return el
  }

  const wrap = div('max-width:240px;font-family:inherit;line-height:1.35')

  const canView = !!onViewListing && !!p.filterId && p.filterId !== HOSPITALS_FILTER_ID
  if (canView) {
    const btn = s(document.createElement('button'), 'font-weight:600;color:#2563eb;font-size:14px;background:none;border:none;padding:0;cursor:pointer;text-align:left')
    btn.textContent = p.name
    btn.addEventListener('click', () => onViewListing!(p.filterId!, p.id))
    wrap.appendChild(btn)
  } else {
    const name = div('font-weight:600;color:#0f172a;font-size:14px')
    name.textContent = p.name
    wrap.appendChild(name)
  }

  if (p.categoryLabel) {
    const cat = div('color:#64748b;font-size:12px;margin-top:1px')
    cat.textContent = p.categoryLabel
    wrap.appendChild(cat)
  }

  if (p.address) {
    const addr = div('color:#334155;font-size:12px;margin-top:6px')
    addr.textContent = p.address
    wrap.appendChild(addr)
  }

  if (p.phone) {
    const phoneRow = div('margin-top:4px;font-size:12px')
    phoneRow.appendChild(a(`tel:${p.phone}`, p.phone, 'color:#2563eb'))
    wrap.appendChild(phoneRow)
  }

  const dirRow = div('margin-top:6px;font-size:12px')
  const verifiedPlaceId = p.raw?.verifiedPlaceId as string | undefined
  const destination = p.address
    ? destinationQuery(p.name, p.address, { alwaysIncludeName: !!verifiedPlaceId })
    : { lat: p.lat, lng: p.lng }
  const dirLink = a(
    directionsUrl(destination, { origin, placeId: (p.raw?.placeId ?? verifiedPlaceId) as string | undefined }),
    'Directions ↗',
    'color:#2563eb',
  )
  dirLink.target = '_blank'; dirLink.rel = 'noopener'
  dirRow.appendChild(dirLink)
  wrap.appendChild(dirRow)

  return wrap
}

// A category pin — noticeably bigger AND wrapped in a pulsing color halo plus
// a one-time drop-bounce when it's the place currently shown in the mobile
// sheet. Scale alone (the old behavior) read as "a little bigger", easy to
// miss at a glance; the halo gives it a lasting visual difference and the
// bounce draws the eye the instant a new pin is picked — the one visual tie
// between "what the sheet is showing" and "where that is on the map".
function buildPin(p: MapPoint, isSelected: boolean): HTMLElement {
  if (!document.getElementById('jpc-pin-select-style')) {
    const style = document.createElement('style')
    style.id = 'jpc-pin-select-style'
    style.textContent =
      '@keyframes jpcPinDrop{0%{transform:translateY(-16px);opacity:0}60%{transform:translateY(2px);opacity:1}100%{transform:translateY(0)}}' +
      '@keyframes jpcPinHalo{0%{transform:scale(.7);opacity:.55}100%{transform:scale(1.6);opacity:0}}'
    document.head.appendChild(style)
  }

  // Precedence: an uploaded category picture (glyphSrc) first — a category
  // with an image set still carries its emoji as the CategoryIcon fallback
  // everywhere else, but on the map itself there's room for only one. Then
  // a hand-built glyph (see lib/categoryIcons.tsx) — a plain "H" string for
  // hospitals, an SVG line icon Element for everything else covered there —
  // which is what most real categories actually get, noticeably cleaner at
  // pin scale than the plain emoji it replaces. Only a category with none of
  // the above (a custom admin-created one with no icon set here yet) falls
  // back to the plain emoji glyph.
  const glyphIcon = p.glyphSrc ? undefined : glyphTextFor(p.filterId) ?? glyphElementFor(p.filterId)
  const pin = new google.maps.marker.PinElement({
    background: p.color,
    borderColor: '#ffffff',
    ...(p.glyphSrc ? { glyphSrc: p.glyphSrc } : glyphIcon ? { glyph: glyphIcon } : { glyph: p.glyph ?? null }),
    // Ignored once `glyph` is an SVG Element (glyphElementFor's icons color
    // themselves white directly) — still applies to a plain-string glyph
    // (the "H" text, or the plain-emoji fallback), where PinElement really
    // does read it.
    glyphColor: '#ffffff',
    scale: isSelected ? 1.6 : 1,
  })
  if (!isSelected && !p.pinned) return pin.element

  const wrap = document.createElement('div')
  wrap.style.cssText =
    'position:relative;display:flex;align-items:flex-end;justify-content:center' +
    (isSelected ? ';animation:jpcPinDrop 0.35s ease-out' : '')
  if (isSelected) {
    const halo = document.createElement('div')
    halo.style.cssText = `position:absolute;bottom:6px;width:30px;height:30px;border-radius:9999px;background:${p.color};animation:jpcPinHalo 1.4s ease-out infinite`
    wrap.append(halo)
  }
  wrap.append(pin.element)
  // A small badge over the pin's own glyph, not a swap to a different marker
  // color/icon — the category color+glyph is how a visitor already tells
  // pins apart at a glance, and a pinned place is still that same category,
  // just also shortlisted. Overlaid at the pin's shoulder (not the tip) so
  // it never covers the glyph itself.
  if (p.pinned) {
    const badge = document.createElement('div')
    badge.style.cssText =
      'position:absolute;top:0;right:0;width:16px;height:16px;border-radius:9999px;' +
      'background:#2563eb;border:2px solid #fff;display:flex;align-items:center;justify-content:center;' +
      'font-size:9px;line-height:1;color:#fff'
    badge.textContent = '📌'
    wrap.appendChild(badge)
  }
  return wrap
}

// Pans so `point` lands in the vertical middle of the map's visible strip —
// the part not covered by the mobile bottom sheet OR the floating search
// bar/category chips overlay at the top — rather than the whole container's
// center, which those would otherwise mostly hide it behind.
//
// panTo(point) alone would put the point at the container's literal center.
// To land it at the middle of [obscuredTopPx, containerHeight - obscuredBottomPx]
// instead, the point needs to move up on screen by
// (obscuredBottomPx - obscuredTopPx) / 2 px from that literal center — shift
// the map's actual center DOWN (south) by that many world-plane units (at the
// current zoom) so the point itself, unmoved, ends up that same distance
// north of the new center, i.e. higher on screen. A bottom-heavy obscurement
// (sheet taller than the top overlay) pushes the point up; a top-heavy one
// (rare — the overlay alone is normally much shorter than the sheet) would
// push it down instead. Falls back to a plain center (no offset) if the
// projection isn't ready yet, rather than not moving at all.
// Same as addListenerOnce(map, 'idle', cb), but cb is guaranteed to run
// within `timeoutMs` even if 'idle' never fires — a real device fires it
// well under a second after a pan/zoom settles, but nothing here can prove
// that always holds (a tile request that stalls, a background tab getting
// starved of rendering time), and the reframe logic below depends on 'idle'
// to know when it's safe to start its NEXT queued camera move. Without a
// fallback, one 'idle' that never arrives would leave every reframe after
// it waiting forever — picking a place would just stop moving the map at
// all, silently, which is worse than the corrupted-position bug this exists
// to prevent.
function onIdleOrTimeout(map: google.maps.Map, timeoutMs: number, cb: () => void) {
  let done = false
  const timer = setTimeout(() => {
    if (done) return
    done = true
    google.maps.event.removeListener(listener)
    cb()
  }, timeoutMs)
  const listener = google.maps.event.addListenerOnce(map, 'idle', () => {
    if (done) return
    done = true
    clearTimeout(timer)
    cb()
  })
}

function panToVisibleCenter(
  map: google.maps.Map,
  point: { lat: number; lng: number },
  obscuredBottomPx: number,
  obscuredTopPx: number,
) {
  const netObscuredPx = obscuredBottomPx - obscuredTopPx
  const projection = netObscuredPx !== 0 ? map.getProjection() : null
  const zoom = map.getZoom()
  if (!projection || zoom == null) {
    map.panTo(point)
    return
  }
  const worldPoint = projection.fromLatLngToPoint(new google.maps.LatLng(point.lat, point.lng))
  if (!worldPoint) {
    map.panTo(point)
    return
  }
  const scale = 2 ** zoom
  const shifted = new google.maps.Point(worldPoint.x, worldPoint.y + (netObscuredPx / 2) / scale)
  const shiftedLatLng = projection.fromPointToLatLng(shifted)
  map.panTo(shiftedLatLng ?? point)
}

// Shifts the map's center by a pixel offset with NO animation — same
// projection math `panToVisibleCenter` uses, but `setCenter` instead of
// `panTo`. Used for the sub-pixel-perfect "nudge" a selection does right
// after its own real (animated) pan/fitBounds already landed roughly in
// place: that nudge is a small correction, not a second destination, and
// animating it too reads as the map moving twice for one tap instead of
// settling once — see the selection-highlight effect's own comment.
function panByInstant(map: google.maps.Map, deltaY: number) {
  const projection = map.getProjection()
  const center = map.getCenter()
  const zoom = map.getZoom()
  if (!projection || !center || zoom == null) return
  const worldPoint = projection.fromLatLngToPoint(center)
  if (!worldPoint) return
  const scale = 2 ** zoom
  const shifted = new google.maps.Point(worldPoint.x, worldPoint.y + deltaY / scale)
  const shiftedLatLng = projection.fromPointToLatLng(shifted)
  if (shiftedLatLng) map.setCenter(shiftedLatLng)
}

// The "you are here" dot: a solid blue marker with a white ring and an
// expanding pulse so it's unmistakable against the category pins. Keyframes are
// injected once, app-wide.
function buildUserDot(): HTMLElement {
  if (!document.getElementById('jpc-userdot-style')) {
    const style = document.createElement('style')
    style.id = 'jpc-userdot-style'
    style.textContent =
      '@keyframes jpcPulse{0%{transform:scale(.5);opacity:.6}70%{transform:scale(2.4);opacity:0}100%{opacity:0}}'
    document.head.appendChild(style)
  }
  const wrap = document.createElement('div')
  wrap.style.cssText = 'position:relative;width:22px;height:22px'
  const pulse = document.createElement('div')
  pulse.style.cssText =
    'position:absolute;inset:0;border-radius:9999px;background:#2563eb;animation:jpcPulse 1.8s ease-out infinite'
  const dot = document.createElement('div')
  dot.style.cssText =
    'position:absolute;inset:5px;border-radius:9999px;background:#2563eb;border:3px solid #fff;box-shadow:0 1px 4px rgba(0,0,0,.45)'
  wrap.append(pulse, dot)
  return wrap
}

/** The interactive Google map: one advanced marker per point, a distinct "you
 *  are here" marker for the visitor, an info window on click, and a viewport
 *  auto-fit to whatever points are currently shown. */
export default function ResourceMap({ points, userLocation, directionsOrigin, follow = true, onResumeFollow, onManualDrag, fallbackCenter = DEFAULT_CENTER, onViewListing, onSelectPoint, onDeselectPoint, onBackgroundClick, onMapLongPress, onLongPressPoint, searchActive, selectedId, frameToken, obscuredBottomPx = 0, obscuredTopPx = 0, zoomRadiusMiles }: Props) {
  const containerRef = useRef<HTMLDivElement>(null)
  const mapRef = useRef<google.maps.Map | null>(null)
  const markersRef = useRef<google.maps.marker.AdvancedMarkerElement[]>([])
  // Markers keyed by point id, alongside the point itself (needed to rebuild
  // a pin when only its selected/unselected style changes) — lets the
  // selection-highlight effect below restyle just the one marker that
  // changed instead of rebuilding the whole marker set on every selection.
  const markersByIdRef = useRef(new Map<string, { marker: google.maps.marker.AdvancedMarkerElement; point: MapPoint }>())
  // The `points` reference the marker-sync effect below last actually
  // rebuilt from — see that effect's own comment for why this exists.
  const syncedPointsRef = useRef<MapPoint[] | null>(null)
  const userMarkerRef = useRef<google.maps.marker.AdvancedMarkerElement | null>(null)
  const infoWindowRef = useRef<google.maps.InfoWindow | null>(null)
  const [ready, setReady] = useState(false)
  const [authFailed, setAuthFailed] = useState(mapsAuthFailed())
  // Right-click's Pin/Unpin menu — see the marker's 'contextmenu' listener
  // below for how this opens. `point` carries whatever pinned state it had
  // at the moment of the right-click; closing-and-reopening the menu after a
  // toggle (rather than patching this in place) keeps it simple, and the
  // menu is only ever open a click or two before it closes anyway.
  const [contextMenu, setContextMenu] = useState<{ point: MapPoint; x: number; y: number } | null>(null)
  const contextMenuRef = useRef<HTMLDivElement>(null)

  // Read these inside the marker effect via refs so it does NOT rebuild markers
  // when the live GPS position ticks or the callback identity changes — only
  // when the actual points change. Rebuilding on every GPS tick was destroying
  // the marker an open info window was anchored to, closing it mid-tap.
  const onViewListingRef = useRef(onViewListing)
  const onSelectPointRef = useRef(onSelectPoint)
  const onDeselectPointRef = useRef(onDeselectPoint)
  const onBackgroundClickRef = useRef(onBackgroundClick)
  const onMapLongPressRef = useRef(onMapLongPress)
  const onLongPressPointRef = useRef(onLongPressPoint)
  const userLocationRef = useRef(userLocation)
  const directionsOriginRef = useRef(directionsOrigin)
  const searchActiveRef = useRef(searchActive)
  const selectedIdRef = useRef(selectedId)
  const obscuredBottomPxRef = useRef(obscuredBottomPx)
  const obscuredTopPxRef = useRef(obscuredTopPx)
  const onManualDragRef = useRef(onManualDrag)
  const zoomRadiusMilesRef = useRef(zoomRadiusMiles)
  useEffect(() => { onViewListingRef.current = onViewListing }, [onViewListing])
  useEffect(() => { onSelectPointRef.current = onSelectPoint }, [onSelectPoint])
  useEffect(() => { onDeselectPointRef.current = onDeselectPoint }, [onDeselectPoint])
  useEffect(() => { onBackgroundClickRef.current = onBackgroundClick }, [onBackgroundClick])
  useEffect(() => { onMapLongPressRef.current = onMapLongPress }, [onMapLongPress])
  useEffect(() => { onLongPressPointRef.current = onLongPressPoint }, [onLongPressPoint])
  useEffect(() => { userLocationRef.current = userLocation }, [userLocation])
  useEffect(() => { directionsOriginRef.current = directionsOrigin }, [directionsOrigin])
  useEffect(() => { searchActiveRef.current = searchActive }, [searchActive])
  useEffect(() => { selectedIdRef.current = selectedId }, [selectedId])
  useEffect(() => { obscuredBottomPxRef.current = obscuredBottomPx }, [obscuredBottomPx])
  useEffect(() => { obscuredTopPxRef.current = obscuredTopPx }, [obscuredTopPx])
  useEffect(() => { onManualDragRef.current = onManualDrag }, [onManualDrag])
  useEffect(() => { zoomRadiusMilesRef.current = zoomRadiusMiles }, [zoomRadiusMiles])
  // ── Initialize the map once ──────────────────────────────────────────────
  useEffect(() => {
    if (!MAPS_API_KEY || mapsAuthFailed()) return
    // Cache Components keeps hidden routes alive under <Activity> instead of
    // unmounting them, so switching tabs away and back re-runs this effect on
    // the SAME already-initialized instance (mapRef/containerRef persist).
    // Without this guard we'd build a second google.maps.Map on top of the
    // still-live one, orphaning the existing markers on the discarded map.
    if (mapRef.current) return
    let cancelled = false
    const unsubscribe = onMapsAuthFailure(() => setAuthFailed(true))

    loadGoogleMaps()
      .then(() => Promise.all([google.maps.importLibrary('maps'), google.maps.importLibrary('marker')]))
      .then(() => {
        if (cancelled || !containerRef.current) return
        mapRef.current = new google.maps.Map(containerRef.current, {
          center: fallbackCenter,
          zoom: 12,
          mapId: MAPS_MAP_ID,
          mapTypeControl: false,
          streetViewControl: false,
          fullscreenControl: false,
          clickableIcons: false,
        })
        infoWindowRef.current = new google.maps.InfoWindow()
        // Click-away to dismiss: tapping empty map closes the open info window
        // and collapses the mobile sheet (marker taps fire 'gmp-click' and
        // don't bubble here, so they still open/select instead).
        mapRef.current.addListener('click', () => {
          infoWindowRef.current?.close()
          onBackgroundClickRef.current?.()
        })
        // Fires only on a genuine user-initiated pan (mouse/touch drag), never
        // from our own programmatic panTo/setCenter calls below — so this is
        // safe to treat as "the user is looking around, stop yanking them
        // back to their live position" without a race against the follow
        // effect's own panning.
        mapRef.current.addListener('dragstart', () => {
          onManualDragRef.current?.()
        })
        // Long-press (touch) and right-click (desktop) both fire as
        // 'contextmenu' — Google's own documented pattern for "the user
        // wants to do something with this exact spot," as opposed to the
        // plain tap/click onBackgroundClick already handles.
        mapRef.current.addListener('contextmenu', (e: google.maps.MapMouseEvent) => {
          if (!e.latLng) return
          e.domEvent?.preventDefault?.()
          onMapLongPressRef.current?.({ lat: e.latLng.lat(), lng: e.latLng.lng() })
        })
        setReady(true)
      })
      .catch(() => {
        if (!cancelled) setAuthFailed(true)
      })

    return () => {
      cancelled = true
      unsubscribe()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // ── One-finger pan / plain-scroll zoom, like the real Google Maps ─────────
  // Google's default ('auto'/'cooperative') asks for two fingers to pan (or
  // ctrl/cmd+scroll to zoom) whenever it thinks the map sits inside a
  // scrollable page — showing a "Use two fingers to move the map" / "Use
  // ctrl + scroll to zoom the map" overlay on the first try instead of just
  // doing it. 'greedy' skips that guard on every platform, matching Google
  // Maps' own site (plain scroll zooms, one-finger/one-drag pans) rather
  // than the more cautious default meant for a map embedded among other
  // scrollable content.
  useEffect(() => {
    mapRef.current?.setOptions({ gestureHandling: 'greedy' })
  }, [ready])

  // ── Keep the map's tile layer in sync with its container's actual size ────
  // Google Maps snapshots its container's dimensions at init and never
  // re-checks them — markers still reposition correctly on a resize (their
  // placement is computed from lat/lng, not pixels), but the tile layer
  // itself stays painted for the old size, leaving mostly-blank gray outside
  // it. Anything that changes the container after mount (this full-bleed
  // mobile layout swapping in, a tab switch, orientation change) needs an
  // explicit nudge — the documented fix is triggering 'resize' and
  // re-applying the center so Maps re-fetches tiles for the new viewport.
  useEffect(() => {
    const map = mapRef.current
    const container = containerRef.current
    if (!ready || !map || !container) return

    const ro = new ResizeObserver(() => {
      const center = map.getCenter()
      google.maps.event.trigger(map, 'resize')
      if (center) map.setCenter(center)
    })
    ro.observe(container)
    return () => ro.disconnect()
  }, [ready])

  // ── Sync category/hospital markers whenever the visible points change ─────
  // The point set the camera was last framed to — see framingKey. Starts
  // empty so the very first real set of points does frame.
  const lastFramedKeyRef = useRef('')

  useEffect(() => {
    const map = mapRef.current
    if (!ready || !map) return
    // Cache Components keeps a hidden route alive under <Activity> instead of
    // unmounting it (see the map-init effect's own comment above), which
    // re-runs every effect — including this one — the moment the visitor
    // switches back to this tab/screen, even though `points` never changed
    // while they were away. Without this guard, every single return trip
    // tore down and rebuilt every marker on the map (new DOM custom elements,
    // new pointerdown/pointermove/pointerup/contextmenu/gmp-click listeners
    // per marker) for no reason — on a category with a lot of pins, that's
    // real synchronous work landing right as the visitor's looking at it,
    // which reads as the map freezing for a beat.
    if (syncedPointsRef.current === points) return

    // A pin toggle produces a brand-new `points` array (see ResourceMapView's
    // `allPoints` memo, which depends on `pinnedIds`) with the exact same
    // places, only some `pinned` flags flipped — same identity problem the
    // comment above already solved for an unrelated re-render, just from a
    // different cause. Falling through to the full rebuild below for that
    // tore down and recreated every marker (new custom elements, new
    // pointerdown/pointermove/pointerup/contextmenu/gmp-click listeners) for
    // a change that visually affects at most one pin. When every point still
    // matches its previous counterpart 1:1 (same id, same geometry, same
    // look) except for `pinned`, patch just the pins whose `pinned` actually
    // changed — the same `marker.content = buildPin(...)` in-place technique
    // the selection-highlight effect below already uses for the same reason.
    const prevPoints = syncedPointsRef.current
    if (prevPoints && prevPoints.length === points.length) {
      let onlyPinnedChanged = true
      for (let i = 0; i < points.length; i++) {
        const a = prevPoints[i]
        const b = points[i]
        if (
          a.id !== b.id || a.lat !== b.lat || a.lng !== b.lng || a.color !== b.color ||
          a.glyph !== b.glyph || a.glyphSrc !== b.glyphSrc || a.name !== b.name
        ) {
          onlyPinnedChanged = false
          break
        }
      }
      if (onlyPinnedChanged) {
        syncedPointsRef.current = points
        for (let i = 0; i < points.length; i++) {
          const p = points[i]
          const entry = markersByIdRef.current.get(p.id)
          if (!entry) continue
          entry.point = p
          if (!!prevPoints[i].pinned !== !!p.pinned) {
            entry.marker.content = buildPin(p, p.id === selectedIdRef.current)
          }
        }
        return
      }
    }

    syncedPointsRef.current = points

    markersRef.current.forEach((m) => (m.map = null))
    markersRef.current = []
    markersByIdRef.current.clear()

    for (const p of points) {
      const marker = new google.maps.marker.AdvancedMarkerElement({
        map,
        position: { lat: p.lat, lng: p.lng },
        title: p.name,
        content: buildPin(p, p.id === selectedIdRef.current),
      })

      // Press-and-hold to toggle Pinned, without also opening the place's
      // card once the hold fires — a real DOM timer, not Maps' own
      // 'contextmenu' long-press synthesis (see onLongPressPoint's own doc
      // comment for why that one doesn't reach individual markers).
      // AdvancedMarkerElement instances are themselves DOM elements (custom
      // elements), so plain pointer listeners work directly on `marker` —
      // and since it's the same node across a content swap (selecting this
      // pin later replaces `marker.content`, not `marker` itself), these
      // never need re-attaching.
      let longPressTimer: ReturnType<typeof setTimeout> | null = null
      let longPressFired = false
      let pressStart = { x: 0, y: 0 }
      // Right-click already opens a proper menu with a Pin/Unpin option (see
      // the 'contextmenu' listener below) — a mouse doesn't need the timer
      // too, and 500ms of held-mouse-button is a touch-native pattern with
      // no visible affordance hinting it does anything on desktop. Tracked
      // per marker rather than checked once, since the same marker element
      // outlives a visitor switching between mouse and touch (a laptop with
      // a touchscreen, say).
      let lastPointerType: string = 'touch'
      const LONG_PRESS_MS = 500
      const MOVE_CANCEL_PX = 10
      function cancelLongPress() {
        if (longPressTimer) {
          clearTimeout(longPressTimer)
          longPressTimer = null
        }
      }
      marker.addEventListener('pointerdown', (e: Event) => {
        const pe = e as PointerEvent
        lastPointerType = pe.pointerType
        if (!onLongPressPointRef.current || pe.pointerType === 'mouse') return
        longPressFired = false
        pressStart = { x: pe.clientX, y: pe.clientY }
        cancelLongPress()
        longPressTimer = setTimeout(() => {
          longPressFired = true
          longPressTimer = null
          if (typeof navigator !== 'undefined' && 'vibrate' in navigator) navigator.vibrate(30)
          onLongPressPointRef.current?.(p)
        }, LONG_PRESS_MS)
      })
      marker.addEventListener('pointermove', (e: Event) => {
        if (!longPressTimer) return
        const pe = e as PointerEvent
        if (Math.hypot(pe.clientX - pressStart.x, pe.clientY - pressStart.y) > MOVE_CANCEL_PX) cancelLongPress()
      })
      marker.addEventListener('pointerup', cancelLongPress)
      marker.addEventListener('pointercancel', cancelLongPress)
      // A touch-and-hold (or desktop right-click) on the marker still fires
      // the browser's native 'contextmenu' event underneath our own timer
      // above, which would otherwise bubble up to the map container's own
      // 'contextmenu' listener (see onMapLongPress) and ALSO open "drop a
      // pin here" at this exact spot. Always swallowed here, before it can
      // bubble — then, for an actual right-click specifically (not a touch
      // long-press synthesizing the same event, which already toggled the
      // pin directly above), open a small Pin/Unpin menu at the cursor: the
      // desktop-native way to discover "there's a hidden action here" that a
      // held mouse button never was.
      marker.addEventListener('contextmenu', (e: Event) => {
        if (!onLongPressPointRef.current) return
        e.preventDefault()
        e.stopPropagation()
        if (lastPointerType !== 'mouse') return
        const me = e as MouseEvent
        setContextMenu({ point: p, x: me.clientX, y: me.clientY })
      })

      marker.addListener('gmp-click', () => {
        // A tap that just fired the long-press above shouldn't ALSO toggle
        // the place's detail card open/closed — that's the "suppress the
        // click" half of the press-and-hold gesture.
        if (longPressFired) {
          longPressFired = false
          return
        }
        if (onSelectPointRef.current) {
          if (selectedIdRef.current === p.id) {
            onDeselectPointRef.current?.()
          } else {
            onSelectPointRef.current(p)
          }
          return
        }
        const iw = infoWindowRef.current
        if (!iw) return
        iw.setContent(buildInfoContent(p, onViewListingRef.current, directionsOriginRef.current ?? userLocationRef.current))
        iw.open({ map, anchor: marker })
      })
      markersRef.current.push(marker)
      markersByIdRef.current.set(p.id, { marker, point: p })
    }

    // Reframe only when the SET of points changed, not merely the array. A
    // pin toggle rebuilds `points` with identical places (see framingKey), and
    // the markers above have already been redrawn with the new pin state by
    // the time we get here — the camera has no business moving for it.
    const key = framingKey(points)
    const framingChanged = key !== lastFramedKeyRef.current
    lastFramedKeyRef.current = key
    if (!framingChanged) return

    // Don't auto-reframe to the points if the visitor has a location set —
    // keeping "where am I" in view matters more than framing every pin —
    // unless a search is actively narrowing them, in which case showing the
    // result(s) takes priority, same as the Google Maps app. When a location
    // IS set during a search, fit both it and the result(s) in view together
    // instead of just the result(s) — so searching for something across town
    // doesn't leave you looking at a result with no idea how far it is from
    // where you are.
    if (userLocationRef.current && searchActiveRef.current) {
      const anchor = userLocationRef.current
      const framed = pointsWithinZoomRadius(points, anchor, zoomRadiusMilesRef.current)
      if (framed.length === 0) {
        // No in-radius results to frame (either genuinely no results, or
        // every match is an outlier the admin's zoom radius excludes) —
        // bounds would otherwise contain only the user's own location, a
        // zero-area box fitBounds snaps to max zoom for (same quirk the
        // points.length === 1 case below already works around). Just
        // recenter on the user's own location at a sane zoom instead.
        map.setCenter(anchor)
        map.setZoom(15)
        return
      }
      const searchBounds = new google.maps.LatLngBounds()
      for (const p of framed) searchBounds.extend(p)
      searchBounds.extend(anchor)
      map.fitBounds(searchBounds, 64)
      return
    }
    if (userLocationRef.current) return
    const anchor = DEFAULT_CENTER
    const framed = pointsWithinZoomRadius(points, anchor, zoomRadiusMilesRef.current)
    if (framed.length === 1) {
      map.setCenter(framed[0])
      map.setZoom(15)
    } else if (framed.length > 1) {
      const framedBounds = new google.maps.LatLngBounds()
      for (const p of framed) framedBounds.extend(p)
      map.fitBounds(framedBounds, 64)
    }
    // Rebuild only when the points themselves change — GPS ticks and callback
    // identity are read via refs so an open info window survives them.
  }, [points, ready])

  // ── Highlight whichever marker matches the sheet's selected place ────────
  // Deliberately its own effect, separate from the marker-rebuild one above —
  // swaps just the two markers involved (old selection back to normal, new
  // one enlarged) instead of rebuilding the whole marker set on every tap.
  const prevSelectedIdRef = useRef<string | undefined>(undefined)
  // Tracks the last frameToken this effect actually acted on, so a
  // selection change only reframes the camera when the parent bumped
  // frameToken alongside it (a list/sidebar pick) — not when it left it
  // untouched (a pin tapped directly on the map, which should just
  // highlight in place without moving the view the visitor already set).
  const consumedFrameTokenRef = useRef(frameToken)
  // Bumped every time a reframe actually starts, so the deferred `idle`
  // callbacks below (registered via addListenerOnce, which Google Maps
  // never cancels) can tell whether they're still the most recent reframe
  // by the time they fire. Without this, a stale callback from a
  // superseded selection could still act using its own (old marker, old
  // padding) closure once it finally gets a turn.
  const reframeTokenRef = useRef(0)
  // True while a reframe's own fitBounds/panTo animation is still in
  // flight (until ITS 'idle' fires). panTo/fitBounds animate over many
  // internal, self-scheduling requestAnimationFrame steps, and the Maps
  // JS API exposes no way to cancel one already running — calling
  // setCenter to "interrupt" it only changes where the map is at that
  // instant, it doesn't stop the OLDER animation's already-queued frames
  // from continuing to fire and calling setCenter again later with ITS
  // OWN (now stale) target. Confirmed live: picking a second place before
  // the first one's animation had finished let the first one's raw target
  // coordinates fire minutes later, well after the second selection had
  // already settled, snapping the camera back toward the first pin.
  // The only reliable fix is to never let two of these animations be in
  // flight on the same map at once — a reframe that starts while the map
  // is still busy from a previous one queues itself for the next idle
  // instead of calling fitBounds/panTo immediately.
  const mapBusyRef = useRef(false)
  useEffect(() => {
    const map = mapRef.current
    if (!ready || !map) return
    const prevId = prevSelectedIdRef.current
    if (prevId && prevId !== selectedId) {
      const prev = markersByIdRef.current.get(prevId)
      if (prev) prev.marker.content = buildPin(prev.point, false)
    }
    if (selectedId && selectedId !== prevId) {
      const current = markersByIdRef.current.get(selectedId)
      if (current) {
        current.marker.content = buildPin(current.point, true)
        const shouldFrame = frameToken !== consumedFrameTokenRef.current
        consumedFrameTokenRef.current = frameToken
        if (shouldFrame) {
          reframeTokenRef.current += 1
          const myReframeToken = reframeTokenRef.current
          // obscuredBottomPx/obscuredTopPx come from three independent
          // ResizeObservers (the map box, the top search/filter overlay, and
          // the sheet height derived from the map box) that don't all settle
          // in the same tick — most visibly right after a phone rotates,
          // where the container briefly reports the OLD (portrait) height
          // while these still hold values sized for it. Left unclamped, that
          // stale padding can exceed the map's actual current height, and
          // fitBounds has no visible room left to fit into — it zooms out as
          // far as it can instead. Capping combined padding to a fraction of
          // the container's real, live-measured height (not the refs' last
          // reported one) keeps a reframe from ever zooming out further than
          // the geometry can actually justify, no matter how stale the
          // padding inputs are.
          const liveContainerHeight = containerRef.current?.getBoundingClientRect().height ?? 0
          const rawBottom = obscuredBottomPxRef.current
          const rawTop = obscuredTopPxRef.current
          let obscured = rawBottom
          let obscuredTop = rawTop
          const rawTotal = rawBottom + rawTop
          const maxTotal = liveContainerHeight * 0.7
          if (liveContainerHeight > 0 && rawTotal > maxTotal) {
            const scale = maxTotal / rawTotal
            obscured = rawBottom * scale
            obscuredTop = rawTop * scale
          }
          // Frame the selected place alongside the visitor's own location,
          // same as a search result — so picking a listing from the sheet
          // (or the sidebar list) shows how far it is from "you are here"
          // instead of just centering on the pin alone. The mobile sheet
          // covers the bottom of the map (and the floating search bar/
          // category chips cover the top), so both are reserved as extra
          // padding — otherwise "centered" bounds would land the pin behind
          // (or right at the edge of) one of them instead of the visible
          // strip between.
          // The above gets the map roughly right, but a pin's geographic
          // anchor is its bottom TIP, not its visual middle — the balloon
          // shape (plus the selected halo) extends well above that point, so
          // centering the anchor alone leaves the pin itself looking
          // noticeably too high. Once the pan/zoom actually settles, measure
          // where the marker's own DOM element really rendered and nudge the
          // rest of the way so the pin graphic — what a person actually
          // looks at — lands centered in the visible strip, not just its
          // invisible anchor point.
          //
          // Instant (panByInstant), not animated: the fitBounds/pan above
          // already did the one real, visible "move to this place" motion —
          // this is a few-pixel correction on top of where that already
          // landed, not a second destination. Animating it too used to make
          // every single selection visibly move the map twice (three times
          // when the zoom-floor branch below also fires), which reads as
          // the map hunting for its spot rather than settling once.
          const nudgeMarkerIntoView = () => {
            if (reframeTokenRef.current !== myReframeToken) return
            const markerEl = current.marker as unknown as HTMLElement
            const mapEl = containerRef.current
            if (!markerEl?.getBoundingClientRect || !mapEl) return
            const markerRect = markerEl.getBoundingClientRect()
            const mapRect = mapEl.getBoundingClientRect()
            const targetCenterY = mapRect.top + obscuredTop + (mapRect.height - obscured - obscuredTop) / 2
            const actualCenterY = markerRect.top + markerRect.height / 2
            const deltaY = actualCenterY - targetCenterY
            if (Math.abs(deltaY) > 2) panByInstant(map, deltaY)
          }
          // Fitting the visitor's own location alongside the pin only pays
          // off when the two are close enough to both land somewhere
          // readable on one small screen — otherwise the bounds between them
          // is mostly just the geography in between (a highway corridor, a
          // river crossing, open county) with neither place actually
          // legible, and on top of that fitBounds may compute too low a
          // zoom to be useful at all (see the zoom-floor correction below,
          // which this sidesteps entirely for a far pick — one motion,
          // never two, and never a frame centered on nothing in particular).
          // Reuses the admin's own "how far still counts as nearby" radius
          // (site_settings.map_zoom_radius_miles) rather than a separate
          // threshold, falling back to a flat 15mi where that's unset.
          const maxFitBothMiles = zoomRadiusMilesRef.current ?? 15
          const isFar =
            userLocationRef.current && haversineMiles(userLocationRef.current, current.point) > maxFitBothMiles
          // Gates the actual fitBounds/panTo calls below so only one of
          // this effect's animated camera moves is ever in flight on the
          // map at a time. A reframe that starts while a previous one is
          // still animating queues itself for the next idle instead of
          // calling fitBounds/panTo right away — seeing mapBusyRef go
          // false again is what tells it the map is actually free, not
          // just that this particular call returned (fitBounds/panTo
          // return immediately; the animation keeps running well after).
          const runReframe = () => {
            if (reframeTokenRef.current !== myReframeToken) return
            if (mapBusyRef.current) {
              onIdleOrTimeout(map, IDLE_FALLBACK_MS, runReframe)
              return
            }
            mapBusyRef.current = true
            if (userLocationRef.current && !isFar) {
              const bounds = new google.maps.LatLngBounds()
              bounds.extend(userLocationRef.current)
              bounds.extend({ lat: current.point.lat, lng: current.point.lng })
              map.fitBounds(bounds, { top: 64 + obscuredTop, left: 64, right: 64, bottom: 64 + obscured })
              onIdleOrTimeout(map, IDLE_FALLBACK_MS, () => {
                mapBusyRef.current = false
                if (reframeTokenRef.current !== myReframeToken) return
                // Safety net for the rare case even a within-range pair still
                // resolves too low a zoom (a short mobile-landscape viewport
                // leaves very little padded room to fit into — see the
                // padding-clamp above) — same floor the "follow my location"
                // effect below uses. <=, not < — a real pair (a Center City
                // anchor and a place a couple miles out, with the mobile
                // sheet's 'half' height plus the top overlay eating well
                // over half the viewport as padding) fit to EXACTLY 13,
                // not below it. At that padding ratio, fitBounds fitting the
                // pair into the thin unobscured strip at the top pushes the
                // camera's own center well past both points to keep them
                // inside it — geometrically correct, but with neither pin
                // anywhere near the visible strip. `< 13` let that exact
                // boundary slip through uncorrected.
                if ((map.getZoom() ?? 0) <= 13) {
                  mapBusyRef.current = true
                  // Zoom BEFORE computing the offset, not after — panToVisibleCenter
                  // converts the sheet/overlay's pixel padding into a geographic
                  // shift using whatever zoom is active when it's called. Called
                  // at the old, much-lower fitBounds zoom (the very thing this
                  // branch exists to correct), the same pixel padding translates
                  // to a real-world distance many times too large — at a low
                  // zoom, each pixel covers far more ground — landing the camera
                  // over a mile from the pin instead of nudging it into view.
                  map.setZoom(14)
                  panToVisibleCenter(map, current.point, obscured, obscuredTop)
                  onIdleOrTimeout(map, IDLE_FALLBACK_MS, () => {
                    mapBusyRef.current = false
                    nudgeMarkerIntoView()
                  })
                  return
                }
                nudgeMarkerIntoView()
              })
            } else {
              // A far pick needs a real zoom-in (it's arriving from whatever
              // the map happened to be showing before, which could be
              // anything) — same single-point convention used elsewhere in
              // this file. No location set at all is different: nothing about
              // this selection implies the visitor's chosen zoom is wrong, so
              // that case leaves it alone rather than forcing one. Set BEFORE
              // panToVisibleCenter, not after — see the zoom-floor branch
              // above for why computing the offset at the OLD zoom (instead
              // of the one it's about to jump to) turns a small padding
              // correction into a real-world offset of a mile or more.
              if (isFar) map.setZoom(15)
              // Either no location set, or the pick is far enough that fitting
              // both wouldn't be useful — just center the pin itself, but
              // still account for the sheet and the top overlay: instead of
              // the whole container's center (which they mostly cover), aim
              // for the middle of the strip still visible between them.
              panToVisibleCenter(map, current.point, obscured, obscuredTop)
              onIdleOrTimeout(map, IDLE_FALLBACK_MS, () => {
                mapBusyRef.current = false
                nudgeMarkerIntoView()
              })
            }
          }
          runReframe()
        }
      }
    }
    prevSelectedIdRef.current = selectedId
  }, [selectedId, ready, frameToken])

  // ── The visitor's "you are here" marker, centered on when set ─────────────
  useEffect(() => {
    const map = mapRef.current
    if (!ready || !map) return

    if (!userLocation) {
      if (userMarkerRef.current) {
        userMarkerRef.current.map = null
        userMarkerRef.current = null
      }
      return
    }

    if (!userMarkerRef.current) {
      const marker = new google.maps.marker.AdvancedMarkerElement({
        map,
        position: userLocation,
        title: 'You are here',
        content: buildUserDot(),
        zIndex: 9999,
      })
      marker.addListener('gmp-click', () => {
        const iw = infoWindowRef.current
        if (!iw) return
        iw.setContent('<div style="font-weight:600;color:#2563eb;font-size:13px">📍 You are here</div>')
        iw.open({ map, anchor: marker })
      })
      userMarkerRef.current = marker
    } else {
      userMarkerRef.current.position = userLocation
    }

    // Only pan/zoom when follow mode is on so the user can browse freely while
    // their dot still moves in the background.
    if (follow) {
      map.panTo(userLocation)
      // <=, not < — kept in sync with the selection-reframe floor above.
      if ((map.getZoom() ?? 0) <= 13) map.setZoom(14)
    }
  }, [userLocation, follow, ready])

  // Dismiss the right-click Pin/Unpin menu the same way any menu should: an
  // outside click, Escape, or the map moving out from under it (panning or
  // zooming would leave it pointing at empty space otherwise). Checked
  // against contextMenuRef, not just "was this inside the menu" — a capture-
  // phase mousedown fires before the menu's own onClick, so closing
  // unconditionally here would unmount the button before its click ever
  // gets to run, which is the actual bug this ref check exists to avoid.
  useEffect(() => {
    if (!contextMenu) return
    const map = mapRef.current
    function close(e?: MouseEvent) {
      if (e && contextMenuRef.current?.contains(e.target as Node)) return
      setContextMenu(null)
    }
    function onKey(e: KeyboardEvent) { if (e.key === 'Escape') close() }
    document.addEventListener('mousedown', close, true)
    document.addEventListener('keydown', onKey)
    const listeners = map ? [map.addListener('bounds_changed', () => close())] : []
    return () => {
      document.removeEventListener('mousedown', close, true)
      document.removeEventListener('keydown', onKey)
      listeners.forEach((l) => l.remove())
    }
  }, [contextMenu])

  const centerOnMe = () => {
    const map = mapRef.current
    if (!map || !userLocation) return
    map.panTo(userLocation)
    map.setZoom(15)
    onResumeFollow?.()
  }

  if (!MAPS_API_KEY || authFailed) {
    return (
      <div className="flex h-full min-h-0 w-full flex-1 items-center justify-center rounded-2xl bg-slate-100 p-6 text-center text-sm text-slate-500">
        The map couldn’t load. Check that the Google Maps API key is configured and the
        Maps JavaScript API is enabled.
      </div>
    )
  }

  return (
    // flex-1/min-h-0 (not a plain h-full percentage) all the way down to the
    // actual map div: a percentage height only resolves against an ancestor
    // with an explicit height, and a flex-grow-resolved height (like this
    // component's own parent uses on the mobile full-bleed map) doesn't
    // count — each level needs to keep passing size down via flex, or
    // everything below silently collapses to 0 height.
    <div className="relative flex h-full min-h-0 w-full flex-1 flex-col">
      {/* -webkit-touch-callout/user-select: without these, iOS Safari treats
          the map tile imagery Google renders inside this div as a long-
          press-able image and pops its own Save/Copy/Share sheet instead of
          letting our pointerdown-timer long-press-to-pin handlers (below)
          fire. */}
      <div
        ref={containerRef}
        className="w-full min-h-0 flex-1 rounded-2xl select-none"
        style={{ WebkitTouchCallout: 'none' }}
      />
      {ready && userLocation && (
        <button
          onClick={centerOnMe}
          // Desktop only — mobile has its own icon-only live-location FAB in
          // this same bottom-right corner (see ResourceMapView), doing the
          // same recenter/resume-follow job; showing both here would be two
          // controls for one action.
          className={`absolute hidden bottom-3 right-3 items-center gap-1.5 rounded-full px-3 py-2 text-sm font-semibold shadow-md ring-1 ring-slate-900/10 cursor-pointer transition-colors desktop:flex ${
            follow
              ? 'bg-blue-600 text-white hover:bg-blue-700'
              : 'bg-white text-blue-600 hover:bg-blue-50'
          }`}
        >
          <span
            className={`inline-block h-2.5 w-2.5 rounded-full ring-2 ${follow ? 'bg-white ring-blue-400' : 'bg-blue-600 ring-white'}`}
            aria-hidden="true"
          />
          {follow ? 'Following' : 'Re-center'}
        </button>
      )}
      {/* Portaled to <body>, same reasoning as CheckboxDropdown's popup: this
          needs to sit above the map (a real DOM element with its own
          stacking, not something z-index inside this component can reliably
          out-rank) and be positioned by viewport coordinates, not wherever
          it'd land in this component's own layout flow. */}
      {contextMenu &&
        createPortal(
          <div
            ref={contextMenuRef}
            role="menu"
            style={{ position: 'fixed', top: contextMenu.y, left: contextMenu.x }}
            className="z-50 -translate-y-1/2 overflow-hidden rounded-lg border border-slate-200 bg-white py-1 shadow-lg"
          >
            <button
              type="button"
              role="menuitem"
              onClick={() => {
                onLongPressPointRef.current?.(contextMenu.point)
                setContextMenu(null)
              }}
              className="flex items-center gap-2 whitespace-nowrap px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50 cursor-pointer"
            >
              <PinIcon filled={contextMenu.point.pinned} className="h-4 w-4 text-slate-500" />
              {contextMenu.point.pinned ? 'Unpin' : 'Pin'}
            </button>
          </div>,
          document.body,
        )}
    </div>
  )
}
